controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller\IndexController::home
    type: attribute
homepage:
 path: /{name}
 controller: App\Controller\IndexController::home